### ISSUE TITLE
o1 fails?

### ISSUE THREAD

**Issue by mitchcapper** [lutzleonhardt/copilot-proxy#1]
First amazing work the proxy does great and easy to setup / follow.   Appreciate you building this bridge and giving such detailed instructions for using it with aider and the like.

For the issue, it seems I may be doing something wrong with o1:

If I dump in vscode the models it seems it is avail and listed just as "o1".   I tried o1-ga although not sure why it said no o1 language model not no o1-ga language model.
```
ERROR: No language model available for model: o1
Request received. Model: o1-ga.
ERROR: No language model available for model: o1
Request received. Model: o1.
```

Trying to use gpt-4o also gave an error but different:
```
ERROR: Error in streaming mode: {"name":"Error","message":"Invalid request: the last message must be a User message."}
Request received. Model: gpt-4o. 
```

I did add these things to the model file directly even to get the aider proxy errors above:
```
- name: o1
  extra_params:
    api_key: n/a
    model: openai/o1
    api_base: http://localhost:14823/v1

- name: GPT-4o
  extra_params:
    api_key: n/a
    api_base: http://localhost:14823/v1   
```

OK nevermind I was able to get around that GPT-4o error message fixing the case,  oddly it showed it in lowercase in VSCode but per above the aider config was upper (even though in aider I did switch to it using /model gpt-4o).
```
- name: gpt-4o
  extra_params:
    api_key: n/a
    api_base: http://localhost:14823/v1    
```

vs dump of Available Copilot Models:
```json
[
  {
    "id": "gpt-3.5-turbo",
    "vendor": "copilot",
    "family": "gpt-3.5-turbo",
    "version": "gpt-3.5-turbo-0613",
    "name": "GPT 3.5 Turbo",
    "maxInputTokens": 12114
  },
  {
    "id": "gpt-4",
    "vendor": "copilot",
    "family": "gpt-4",
    "version": "gpt-4-0613",
    "name": "GPT 4",
    "maxInputTokens": 28501
  },
  {
    "id": "gpt-4o",
    "vendor": "copilot",
    "family": "gpt-4o",
    "version": "gpt-4o-2024-05-13",
    "name": "GPT 4o",
    "maxInputTokens": 63827
  },
  {
    "id": "gpt-4o-mini",
    "vendor": "copilot",
    "family": "gpt-4o-mini",
    "version": "gpt-4o-mini-2024-07-18",
    "name": "GPT 4o Mini",
    "maxInputTokens": 12115
  },
  {
    "id": "o1",
    "vendor": "copilot",
    "family": "o1-ga",
    "version": "o1-2024-12-17",
    "name": "o1 (Preview)",
    "maxInputTokens": 19827
  },
  {
    "id": "o3-mini",
    "vendor": "copilot",
    "family": "o3-mini",
    "version": "o3-mini-2025-01-31",
    "name": "o3-mini (Preview)",
    "maxInputTokens": 19827
  },
  {
    "id": "claude-3.5-sonnet",
    "vendor": "copilot",
    "family": "claude-3.5-sonnet",
    "version": "claude-3.5-sonnet",
    "name": "Claude 3.5 Sonnet (Preview)",
    "maxInputTokens": 85734
  },
  {
    "id": "gemini-2.0-flash-001",
    "vendor": "copilot",
    "family": "gemini-2.0-flash",
    "version": "gemini-2.0-flash-001",
    "name": "Gemini 2.0 Flash (Preview)",
    "maxInputTokens": 127827
  }
]
```

**Comment by lutzleonhardt** [comment]
Hi Mitch,

Glad you like it :)
I think you need a payed subscription to get access to the more advanced models:

![Image](https://github.com/user-attachments/assets/88defcc2-1fda-4256-8a77-625aee2e9be5)

o3-mini is only icluded as a preview without having a sub.

![Image](https://github.com/user-attachments/assets/12ea50b8-8ea4-4bb2-b96f-d9c8e2ed62d5)

**Comment by lutzleonhardt** [comment]
@mitchcapper Feel free to reopen the issue if this is not the problem

**Comment by mitchcapper** [comment]
I can't reopen but yeah not the problem:)  Claude, GPT 4o, o3-mini all just fine.  I assume Gemini wouldn't as not an openai style endpoint I believe.  It at least believes in itself:

![Image](https://github.com/user-attachments/assets/821713d4-f73f-4df4-8ed0-41a79b19327b)

**Comment by lutzleonhardt** [comment]
OK, so it means you have a payed Sub for Copilot?

**Comment by mitchcapper** [comment]
Sorry yes their maintainer gifted sub which I believe is direct equivalent of their  copilot pro.   I can use O1 as my model in VS code without a problem.

**Comment by lutzleonhardt** [comment]
Gemini 2 Flash works for me with this config:

``` yaml
- name: gemini-2.0-flash-001
  extra_params:
    model: openai/gemini-2.0-flash
    api_key: n/a
    api_base: http://localhost:3000/v1
```

![Image](https://github.com/user-attachments/assets/b64515a2-5da5-4c3b-a49e-24bf5401a9a2)

This line (the prefix `openai`) is telling aider/liteLLM that the endpoint is an openai-like endpoint
`model: openai/gemini-2.0-flash`

**Comment by lutzleonhardt** [comment]
@mitchcapper 

Can you try this for o1 (I have no sub):

```yaml
- name: o1
  straming: false
  extra_params:
    model: openai/o1-ga
    api_key: n/a
    api_base: http://localhost:3000/v1
```

I am not sure about streaming on or off...
